[package]
name = "docs"
version = "0.1.0"
edition = "2021"

[lib]
name = "docs_lib"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.147"
serde_json = "1.0.87"
rustdoc-types = "0.19.0"
